### PR TITLE
Fix https://github.com/mitchellh/packer/issues/1752 - broken shell script

### PR DESCRIPTION
**Pull request by jtblin**
Cf. commit from https://github.com/mitchellh/packer/commit/3a286ab6bdba7b8e5bf6a43c357a0ffeacd3dc97

### CODE REVIEW

**Comment by jtblin** [comment]
@ColinHebert @levilovelock @pleschev

**Comment by jtblin** [comment]
Ping

**Comment by ojongerius** [comment]
@ColinHebert  / @levilovelock any reason why you guys did not merge this?

**Comment by levpaul** [comment]
Nope! I didn't see it. It's from upstream? LGTM

**Comment by ojongerius** [comment]
:+1:

**Comment by jtblin** [comment]
Thank you!

**Pull request merged**
